//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace decomposeDividers.WebServiceDividers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceDividers.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InputValue", ReplyAction="*")]
        decimal InputValue(decimal number);
        
        // CODEGEN: Generating message contract since element name ListDividersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListDividers", ReplyAction="*")]
        decomposeDividers.WebServiceDividers.ListDividersResponse ListDividers(decomposeDividers.WebServiceDividers.ListDividersRequest request);
        
        // CODEGEN: Generating message contract since element name ListPrimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPrime", ReplyAction="*")]
        decomposeDividers.WebServiceDividers.ListPrimeResponse ListPrime(decomposeDividers.WebServiceDividers.ListPrimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDividersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDividers", Namespace="http://tempuri.org/", Order=0)]
        public decomposeDividers.WebServiceDividers.ListDividersRequestBody Body;
        
        public ListDividersRequest() {
        }
        
        public ListDividersRequest(decomposeDividers.WebServiceDividers.ListDividersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListDividersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal number;
        
        public ListDividersRequestBody() {
        }
        
        public ListDividersRequestBody(decimal number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDividersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListDividersResponse", Namespace="http://tempuri.org/", Order=0)]
        public decomposeDividers.WebServiceDividers.ListDividersResponseBody Body;
        
        public ListDividersResponse() {
        }
        
        public ListDividersResponse(decomposeDividers.WebServiceDividers.ListDividersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListDividersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public decomposeDividers.WebServiceDividers.ArrayOfDecimal ListDividersResult;
        
        public ListDividersResponseBody() {
        }
        
        public ListDividersResponseBody(decomposeDividers.WebServiceDividers.ArrayOfDecimal ListDividersResult) {
            this.ListDividersResult = ListDividersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPrimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPrime", Namespace="http://tempuri.org/", Order=0)]
        public decomposeDividers.WebServiceDividers.ListPrimeRequestBody Body;
        
        public ListPrimeRequest() {
        }
        
        public ListPrimeRequest(decomposeDividers.WebServiceDividers.ListPrimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPrimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal number;
        
        public ListPrimeRequestBody() {
        }
        
        public ListPrimeRequestBody(decimal number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPrimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPrimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public decomposeDividers.WebServiceDividers.ListPrimeResponseBody Body;
        
        public ListPrimeResponse() {
        }
        
        public ListPrimeResponse(decomposeDividers.WebServiceDividers.ListPrimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPrimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public decomposeDividers.WebServiceDividers.ArrayOfDecimal ListPrimeResult;
        
        public ListPrimeResponseBody() {
        }
        
        public ListPrimeResponseBody(decomposeDividers.WebServiceDividers.ArrayOfDecimal ListPrimeResult) {
            this.ListPrimeResult = ListPrimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : decomposeDividers.WebServiceDividers.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<decomposeDividers.WebServiceDividers.Service1Soap>, decomposeDividers.WebServiceDividers.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal InputValue(decimal number) {
            return base.Channel.InputValue(number);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        decomposeDividers.WebServiceDividers.ListDividersResponse decomposeDividers.WebServiceDividers.Service1Soap.ListDividers(decomposeDividers.WebServiceDividers.ListDividersRequest request) {
            return base.Channel.ListDividers(request);
        }
        
        public decomposeDividers.WebServiceDividers.ArrayOfDecimal ListDividers(decimal number) {
            decomposeDividers.WebServiceDividers.ListDividersRequest inValue = new decomposeDividers.WebServiceDividers.ListDividersRequest();
            inValue.Body = new decomposeDividers.WebServiceDividers.ListDividersRequestBody();
            inValue.Body.number = number;
            decomposeDividers.WebServiceDividers.ListDividersResponse retVal = ((decomposeDividers.WebServiceDividers.Service1Soap)(this)).ListDividers(inValue);
            return retVal.Body.ListDividersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        decomposeDividers.WebServiceDividers.ListPrimeResponse decomposeDividers.WebServiceDividers.Service1Soap.ListPrime(decomposeDividers.WebServiceDividers.ListPrimeRequest request) {
            return base.Channel.ListPrime(request);
        }
        
        public decomposeDividers.WebServiceDividers.ArrayOfDecimal ListPrime(decimal number) {
            decomposeDividers.WebServiceDividers.ListPrimeRequest inValue = new decomposeDividers.WebServiceDividers.ListPrimeRequest();
            inValue.Body = new decomposeDividers.WebServiceDividers.ListPrimeRequestBody();
            inValue.Body.number = number;
            decomposeDividers.WebServiceDividers.ListPrimeResponse retVal = ((decomposeDividers.WebServiceDividers.Service1Soap)(this)).ListPrime(inValue);
            return retVal.Body.ListPrimeResult;
        }
    }
}
